applications/department/urls.py
from django.urls import path, include
from . import views

app_name = 'departament_app'

urlpatterns = [
    path('new-department/', views.NewDepartmentView.as_view(), name ='new-deparment'),
    path('list-department/', views.DepartamentListView.as_view(), name ='list-deparment')
]

applications/person/urls.py
from django.urls import path, include
from .models import Employee
from . import views
from .views import ListAllEmployee, SuccessView, ListByDepartment, EmployeeCreateView


# class EmployeeConfig(AppConfig):
#     default_auto_field = 'django.db.models.BigAutoField'
#     name = 'applications.person'

app_name = 'person_app'

urlpatterns = [
    path('all-employees/', views.ListAllEmployee.as_view(), name = 'all_employees'),
    path('SuccessView/', views.SuccessView.as_view(), name = 'correct'),
    # path('ListByDepartmentFinances/', views.ListByDepartment.as_view()),
    path('two-employees/', views.ListAllEmployeeByFour.as_view()),
    path('ListByDepartment/<short_name>', views.ListByDepartment.as_view(), name = 'listByDepartment'),
    path('ListByWord/', views.ListByDepartmentByWord.as_view()),
    path('ListEmployeeAbility/', views.ListAbilityEmployeeWithIdOne.as_view()),
    path('EmployeeDetailView/<pk>', views.EmployeeDetailView.as_view()),
    path('EmployeeDetailViewKwargs/<pk>', views.EmployeeDetailViewKwargs.as_view(), name='empleado_detail'),
    path('addEmployee/', views.EmployeeCreateView.as_view(), name='add_employee'),
    path('EditEmployee/<pk>/', views.EmployeeUpdateView.as_view(), name='modify_employee'),
    path('DeleteEmployee/<pk>/', views.DeleteEmployeeView.as_view(), name='delete_employee'),
    path('', views.InicioView.as_view(), name='Inicio'),
    path('list-employees-admin/', views.ListEmployeeAdmin.as_view(), name='list-employees-admin')
]

test_project/urls.py
from django.contrib import admin #Trae las plantillas de admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.department.urls')),
    path('', include('applications.person.urls')),
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/department/models.py
from django.db import models

# Create your models here.

class Department(models.Model):
    name_deparment = models.CharField('Name', max_length=20, default='')
    short_name = models.CharField('Short name', max_length=20, default='')
    anulate = models.BooleanField('Anulate', default=False)

    def __str__(self):
        return self.name_deparment+ ' - '+self.short_name
    
    class Meta:
        ordering = ['-name_deparment']
        verbose_name_plural = 'Department'

applications/department/forms.py
from django import forms

class NewDepartmentForm(forms.Form):
    name = forms.CharField(max_length=15)
    last_name = forms.CharField(max_length=15)
    name_deparment = forms.CharField(max_length=15)
    short_name = forms.CharField(max_length=15)

applications/department/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from .forms import NewDepartmentForm
from .models import Department
from applications.person.models import Employee

class NewDepartmentView(FormView):
    template_name = 'department/new_department.html'
    form_class = NewDepartmentForm
    success_url = '/'

    # def valid(self, form):
    #     return super(NewDepartmentForm, self).form_valid(form)

    def form_valid(self, form):
        print("Estamos en el form valid")
        depa = Department(
            # Atributos del modelo = A lo que definimos en el formulario y pedimos en el HTML
            name_deparment = form.cleaned_data['name_deparment'],
            short_name = form.cleaned_data['short_name'],
        )

        depa.save()

        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']

        Employee.objects.create(
            name = name,
            last_name = last_name,
            position = '3',
            department = depa,
        )
        return super(NewDepartmentView, self).form_valid(form)
    

class DepartamentListView(ListView):
    model = Department
    template_name = 'department/list.html'
    context_object_name = 'departaments'

test_project/templates/department/list.html
{% extends 'base.html' %}

{% block contect %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">List Departaments</h1>
            <h1 class="cell">
                <table>
                    <tbody>
                        {% for depart in departaments %}
                        <tr>
                            <td>{{depart.name_deparment}}</td>
                            <td>{{depart.short_name}}</td>
                            <td><a href="{% url 'person_app:listByDepartment' depart.short_name %}" class="button warning">Show details</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </h1>
        </div>
    </div>
{% endblock contect %}

test_project/templates/department/new_department.html
{% extends 'base.html' %}

{% block title %}
    Registrar Departamento
{% endblock title %}

{% block contect %}
    {% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Registrar Departamento
        </h1>
        <div>
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}

                <div class="cell large-6">
                    <label >Nombre(s):
                    <label >{{ form.name }}</1abel>
                    </label>
                </div>
                <div class="cell large-6">
                    <label >Apellido(s):
                    <label >{{ form.last_name }}</1abel>
                    </label>
                </div>
                <div class="cell large-6">
                    <label >Departamento(s):
                    <label >{{ form.name_deparment }}</1abel>
                    </label>
                </div>
                <div class="cell large-6">
                    <label >Departamento corto(s):
                    <label >{{ form.short_name }}</1abel>
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock contect %}