applications/person/urls.py
from django.urls import path, include
from .models import Employee
from . import views
from .views import ListAllEmployee, SuccessView, ListByDepartment, EmployeeCreateView


# class EmployeeConfig(AppConfig):
#     default_auto_field = 'django.db.models.BigAutoField'
#     name = 'applications.person'

app_name = 'person_app'

urlpatterns = [
    path('all-employees/', views.ListAllEmployee.as_view(), name = 'all_employees'),
    path('SuccessView/', views.SuccessView.as_view(), name = 'correct'),
    # path('ListByDepartmentFinances/', views.ListByDepartment.as_view()),
    path('two-employees/', views.ListAllEmployeeByFour.as_view()),
    path('ListByDepartment/<short_name>', views.ListByDepartment.as_view(), name = 'listByDepartment'),
    path('ListByWord/', views.ListByDepartmentByWord.as_view()),
    path('ListEmployeeAbility/', views.ListAbilityEmployeeWithIdOne.as_view()),
    path('EmployeeDetailView/<pk>', views.EmployeeDetailView.as_view()),
    path('EmployeeDetailViewKwargs/<pk>', views.EmployeeDetailViewKwargs.as_view(), name='empleado_detail'),
    path('addEmployee/', views.EmployeeCreateView.as_view(), name='add_employee'),
    path('EditEmployee/<pk>/', views.EmployeeUpdateView.as_view(), name='modify_employee'),
    path('DeleteEmployee/<pk>/', views.DeleteEmployeeView.as_view(), name='delete_employee'),
    path('', views.InicioView.as_view(), name='Inicio'),
    path('list-employees-admin/', views.ListEmployeeAdmin.as_view(), name='list-employees-admin')
]

test_project/urls.py
from django.contrib import admin #Trae las plantillas de admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.department.urls')),
    path('', include('applications.person.urls')),
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/person/models.py
from django.db import models
from applications.department.models import Department
from ckeditor.fields import RichTextField

# Create your models here.

class Ability(models.Model):
    ability = models.CharField('Ability', max_length=50)

    class Meta:
        verbose_name_plural = 'Abilities'

    def __str__(self):
        return self.ability

class Employee(models.Model):

    JOB_CHOICES = (
        ('0', 'Finances'),
        ('1', 'Admin'),
        ('2', 'Developer'),
        ('3', 'Other'),
    )

    name = models.CharField('Name', max_length=20, default='')
    last_name = models.CharField('Last name', max_length=20, default='')
    position = models.CharField('Position', max_length=20, default='', choices=JOB_CHOICES)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, default='')
    anulate = models.BooleanField('Anulate', default=False)
    ability = models.ManyToManyField(Ability)
    full_name = models.CharField('Full Name', max_length=20, blank=True) #Podemos comentar lo del admin
    avatar = models.ImageField(upload_to='Employee', blank=True, null=True)
    life_sheet = RichTextField()

    class Meta:
        ordering = ['last_name', 'name']
        verbose_name_plural = 'My employee'
        verbose_name_plural = 'Company employee'

    

    def __str__(self):
        return str(self.id) + ' - ' + self.last_name + ' - ' + self.name + ' - ' + str(self.department)

applications/person/forms.py
from django import forms

from .models import Employee

class EmployeeForm(forms.ModelForm):

    class Meta:
        model = Employee
        fields = (
            "name",
            "last_name",
            "position",
            "department",
            "avatar",
            "ability",
        )
        widgets = {
            'ability': forms.CheckboxSelectMultiple()
        }

applications/person/views.py
from django.db import models
from django.db.models.query import QuerySet
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.base import TemplateView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.views.generic.edit import DeleteView
from .models import Employee
from django.urls import reverse_lazy
from .forms import EmployeeForm

# Create your views here.
class ListAllEmployee(ListView):
    template_name = "person/list_all.html"
    paginate_by = 5
    model = Employee
    context_object_name = 'employee_list'
    ordering = "name"
    
    def get_queryset(self):
        key_word = self.request.GET.get("kword", '')
        list = Employee.objects.filter(
            name__icontains = key_word
        )
        return list

class SuccessView(TemplateView):
    template_name = "person/success.html"

# class ListByDepartmentFinances(ListView):
#     template_name = "person/list_area_finances.html"
#     queryset = Employee.objects.filter(department__name='Finances')
#     context_object_name = 'employee_list'

class ListByDepartment(ListView):
    template_name = "person/list_area.html"
    context_object_name = 'employees'
    
    def get_queryset(self):
        area = self.kwargs['short_name']
        employee_list = Employee.objects.filter(department__short_name=area)
        return employee_list
    
class ListByDepartmentByWord(ListView):
    template_name = "person/list_by_word.html"
    context_object_name = 'employee'
    
    
    def get_queryset(self):
        key_word = self.request.GET.get("kword", '') #Etiqueta HTML
        print('========>', key_word)
        employee = Employee.objects.filter(name=key_word)
        print('========> Resutl:', employee)
        print('')
        return employee
    
class ListAllEmployeeByFour(ListView):
    template_name = "person/list_all.html"
    paginate_by = 2
    model = Employee
    ordering = "name"
    context_object_name = 'employee_list'

class ListAbilityEmployeeWithIdOne(ListView):
    template_name = 'person/ability.html'
    context_object_name = 'ability'

    def get_queryset(self):
        employee = Employee.objects.get(id=1)
        return employee.ability.all()
    
class EmployeeDetailView(DetailView):
    model = Employee
    template_name = 'person/EmployeeDetailView.html'
    context_object_name = 'employee_detail'

class EmployeeDetailViewKwargs(DetailView):
    model = Employee
    template_name = 'person/EmployeeDetailViewKwargs.html'
    context_object_name = 'employee_detail_kwargs'

    def get_context_data(self, **kwargs):
        context = super(EmployeeDetailViewKwargs, self).get_context_data(**kwargs)
        context['title'] = 'Month employee'
        return context

class EmployeeCreateView(CreateView):
    model = Employee
    template_name = 'person/addEmployee.html'
    # fields = ('__all__')
    # success_url = '/SuccessView'
    fields = [
        'name',
        'last_name',
        'position',
        'department',
        'ability',
        'avatar'
    ]
    success_url = reverse_lazy('person_app:correct')

    def form_valid(self, form): 
        employee = form.save()
        employee.full_name = employee.name + ' - ' + employee.last_name
        employee.save()
        return super(EmployeeCreateView, self).form_valid(form)
    
class EmployeeUpdateView(UpdateView):
    model = Employee
    template_name = 'person/update.html'
    fields = [
        'name',
        'last_name',
        'position',
        'department',
        'ability',
    ]

    success_url = reverse_lazy('person_app:correct')

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        # print('********** POST_METHOD **********')
        # print('*********************************')
        print(request.POST)
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        # employee = form.save()
        # employee.full_name = employee.name + ' - ' + employee.last_name
        # employee.save()
        # return super(EmployeeCreateView, self).form_valid(form)
        # print('********** FORM_VALID ***********')
        # print('*********************************')
        return super(EmployeeUpdateView, self).form_valid(form)
    
class DeleteEmployeeView(DeleteView):
    model = Employee
    template_name = 'person/deleteEmployee.html'   
    success_url = reverse_lazy('person_app:correct')

class InicioView(TemplateView):
    template_name = "inicio.html"     

class ListEmployeeAdmin(ListView):
    template_name = 'person/list_employees.html'
    paginate_by = 10
    ordering = 'name'
    context_object_name = 'employees'
    model = Employee

class EmployeeCreateViewForm(CreateView):
    template_name = 'person/add_employee_form.html'
    model = Employee
    form_class = EmployeeForm
    success_url = reverse_lazy('person_app:correct')

    def form_valid(self, form):
        employee = form.save(commit=False)
        employee.full_name = employee.name + ' ' + employee.last_name
        employee.save()
        return super(EmployeeCreateViewForm, self).form_valid(form)

test_project/templates/person/EmployeeDetailView.html
<h1>Employee Detail {{title}} </h1>

{{ employee_detail_kwargs }}

<h1>Details</h1>

<p>{{ employee_detail_kwargs.name }}</p>
<p>{{ employee_detail_kwargs.last_name }}</p>
<p>{{ employee_detail_kwargs.position }}</p>
<p>{{ employee_detail_kwargs.department }}</p>
<p>{{ employee_detail_kwargs.ability }}</p>

test_project/templates/person/EmployeeDetailViewKwargs.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{ employee_detail_kwargs.last_name }} {{ employee_detail_kwargs.name }}
{% endblock title %}

{% block contect %}
    {% include 'includes/header.html' %}
    <div class="grid-container align-center">
        <div class="grid-x">
            <center>
                <h1 class="cell">Datails Employee</h1>
            </center>
            <div class="cell">
                <form class="grid-x grid-margin-x align-center" method="POST">{% csrf_token %}
                    <div class="cell large-4 card" style="width: 300px;">
                        <div class="card-divider">
                            {{ employee_detail_kwargs.get_job_display }}
                        </div>
                        {% if employee_detail_kwargs.avatar %}
                            <img src="{{ employee_detail_kwargs.avatar.url }}">
                        {% else %}
                            <img src="../../../static/img/anonimous.png">
                        {% endif %}
                        <div class="card-section">
                            <h4>{{ employee_detail_kwargs.name }} {{ employee_detail_kwargs.last_name }}</h4>
                            <p>{{ employee_detail_kwargs.departament }}</p>
                            <p><span class="label">Habilidades:</span></p>
                            <ul class="vertical menu">
                                {% for h in employee_detail_kwargs.ability.all %}
                                <li>
                                    {{ h.ability }}
                                </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </form>
            </div>
        
        </div>
    </div>
{% endblock contect %}

test_project/templates/person/ability.html
<h1>Ability</h1>

<ul>
    
    {% for h in ability %}
        <li>{{h}}</li>
    {% endfor %}
        
</ul>

test_project/templates/person/addEmployee.html
{% extends 'base.html' %}

{% block title %}
    Registrar Empleado
{% endblock title %}

{% block contect %}
    {% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Registrar Empleado
        </h1>
        <div>
            <form class="grid-x grid-margin-x" method="POST" enctype="multipart/form-data">{% csrf_token %}

                <div class="cell large-6">
                    <label >Nombre(s):
                    <label >{{ form.name }}</1abel>
                    </label>
                </div>
                <div class="cell large-6">
                    <label >Apellido(s):
                    <label >{{ form.last_name }}</1abel>
                    </label>
                </div>
                <div class="cell large-6">
                    <label >Trabajo(s):
                    <label >{{ form.position }}</1abel>
                    </label>
                </div>
                <div class="cell large-6">
                    <label >Departamento(s):
                    <label >{{ form.department }}</1abel>
                    </label>
                </div>
                <div class="cell large-6">
                    <label >Habilidades(s):
                    <label >{{ form.ability }}</1abel>
                    </label>
                </div>
                <div class="cell large-6">
                    <label >Avatar(s):
                    <label >{{ form.avatar }}</1abel>
                    </label>
                </div>
                <div class="cell">
                    <button type="submit" class="success button">Agregar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock contect %}

test_project/templates/person/deleteEmployee.html
{% extends 'base.html' %}

{% block title %}
    Eliminar Empleado
{% endblock title %}

{% block contect %}
    {% include 'includes/header.html' %}
<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">
            Eliminar Empleado
        </h1>
        <div class="cell">
            <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}
                <div class="callout secondary">
                    <label>
                        <h5>¿ Desea eliminar el empleado {{ object.name }} {{ object.last_name }} ? </h5>
                        <button type="submit" class="alert button">Confirmar</button>
                    </label>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock contect %}

test_project/templates/person/list_all.html
{% extends 'base.html' %}

{% block contect %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Buscar Empleado...">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th width="200">ID</th>
                        <Th>NOMBRES</th>
                        <th width="150">APELLIDOS</th>
                        <th width="150">DEPARTAMENTO</th>
                        <th width="150">ACCIÓN</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in employee_list %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.name}}</td>
                        <td>{{ e.last_name}}</td>
                        <td>{{ e.department}}</td>
                        <td><a class="button warning" href="{% url 'person_app:empleado_detail' e.id %}" >Ver</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">

                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}">{{ pagina }} Atrás</a>
                        </li>
                    {% endif %}
                    {% for pagina in paginator.page_range %}

                        {% if pagina == page_obj.number %}
                            <li class="current"><span class="show-for-sr">Tu estás en la página </span>{{ pagina }}</1i>
                            {% else %}
                            <li class=""><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                        {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}">{{ pagina }} Siguiente</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
                    {% endif %}
        </div>
    </div>
</div>
{% endblock contect %}

test_project/templates/person/list_all_1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Compressed CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.7.5/dist/css/foundation.min.css" crossorigin="anonymous">
    <!-- Compressed JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.7.5/dist/js/foundation.min.js" crossorigin="anonymous"></script>
</head>
    <body>
        <h1>All employees</h1>
        <ul>
            
            {% for e in employee_list %}
                <li>{{e}}</li>
            {% endfor %}
                
        </ul>
    </body>
</html>

test_project/templates/person/list_area.html
{% block title %}
    List employees:
{% endblock title %}

{% block content %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <div class="cell"><h1>Employee by:</h1></div>
                <div class="cell">
                    <table>
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Last name</th>
                                <th>Department</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for e in employees%}
                            <tr>
                                <td>{{ e.id }}</td>
                                <td>{{ e.name }}</td>
                                <td>{{ e.last_name }}</td>
                                <td>{{ e.department }}</td>
                                <td><a href="{% url 'person_app:empleado_detail' e.id %}" class="button warning">Show</a></td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="cell">
                    {% if is_paginated %}
                <nav aria-label="Pagination">
                <ul class="pagination">

                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}">{{ pagina }} Atrás</a>
                        </li>
                    {% endif %}
                    {% for pagina in paginator.page_range %}

                        {% if pagina == page_obj.number %}
                            <li class="current"><span class="show-for-sr">Tu estás en la página </span>{{ pagina }}</1i>
                            {% else %}
                            <li class=""><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                        {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}">{{ pagina }} Siguiente</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
                    {% endif %}
        </div>
    </div>
</div>
{% endblock content %}

test_project/templates/person/list_area_finances.html
<h1>Area Finances</h1>
<ul>
    
    {% for e in employee_list %}
        <li>{{e}}</li>
    {% endfor %}
        
</ul>

test_project/templates/person/list_by_word.html
<h1>Filter By Word</h1>

<form method="GET">{% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Enter the name">
    <button type="submit">Search</button>
</form>

<h1>Result</h1>

<ul>
    {% for e in employee %}
        <li>{{ e }}</li>
    {% endfor %}
        
</ul>

test_project/templates/person/list_employees.html
{% extends 'base.html' %}

{% block contect %}
{% include 'includes/header.html' %}

<div class="grid-container">
    <div class="grid-x">
        <h1 class="cell">Lista Empleados</h1>
        <form class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
            <div class="cell large-7">
                <input type="text" id="kword" name="kword" placeholder="Buscar Empleado...">
            </div>
            <div class="cell large-2">
                <button type="submit" class="success button">Buscar</button>
            </div>
        </form>
        <div class="cell">
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>NOMBRES</th>
                        <th>APELLIDOS</th>
                        <th>DEPARTAMENTO</th>
                        <th>ACCIÓN</th>
                    </tr>
                </thead>
                <tbody>
                    {% for e in employees %}
                    <tr>
                        <td>{{ e.id }}</td>
                        <td>{{ e.name}}</td>
                        <td>{{ e.last_name}}</td>
                        <td>{{ e.department}}</td>
                        <td>
                            <a class="button success" href="{% url 'person_app:modify_employee' e.id %}">Modificar</a>
                            <a class="button alert" href="{% url 'person_app:delete_employee' e.id %}">Eliminar</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="cell">
            {% if is_paginated %}
            <nav aria-label="Pagination">
                <ul class="pagination">

                    {% if page_obj.has_previous %}
                        <li class="pagination-previous">
                            <a href="?page={{ page_obj.previous_page_number }}">{{ pagina }} Atrás</a>
                        </li>
                    {% endif %}
                    {% for pagina in paginator.page_range %}

                        {% if pagina == page_obj.number %}
                            <li class="current"><span class="show-for-sr">Tu estás en la página </span>{{ pagina }}</1i>
                            {% else %}
                            <li class=""><a href="?page={{ pagina }}">{{ pagina }}</a></li>
                        {% endif %}

                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="pagination-next">
                            <a href="?page={{ page_obj.next_page_number }}">{{ pagina }} Siguiente</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
                    {% endif %}
        </div>
    </div>
</div>
{% endblock contect %}

test_project/templates/person/success.html
<h1>Success action!!!</h1>

test_project/templates/person/update.html
{% extends 'base.html' %}

{% block title %}
    Editar Empleado
{% endblock title %}

{% block contect %}
    {% include 'includes/header.html' %}
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">
                Modificar Empleado
            </h1>
            <div>
                <form class="grid-x grid-margin-x" method="POST">{% csrf_token %}

                    <div class="cell large-6">
                        <label >Nombre(s):
                        <label >{{ form.name }}</1abel>
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label >Apellido(s):
                        <label >{{ form.last_name }}</1abel>
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label >Trabajo(s):
                        <label >{{ form.position }}</1abel>
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label >Departamento(s):
                        <label >{{ form.department }}</1abel>
                        </label>
                    </div>
                    <div class="cell large-6">
                        <label >Habilidades(s):
                        <label >{{ form.ability }}</1abel>
                        </label>
                    </div>
                    <div class="cell">
                        <button type="submit" class="success button">Actualizar</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock contect %}