applications/department/urls.py
from django.urls import path, include
from . import views

app_name = 'departament_app'

urlpatterns = [
    path('new-department/', views.NewDepartmentView.as_view(), name ='new-deparment'),
    path('list-department/', views.DepartamentListView.as_view(), name ='list-deparment')
]

applications/person/urls.py
from django.urls import path, include
from .models import Employee
from . import views
from .views import ListAllEmployee, SuccessView, ListByDepartment, EmployeeCreateView


# class EmployeeConfig(AppConfig):
#     default_auto_field = 'django.db.models.BigAutoField'
#     name = 'applications.person'

app_name = 'person_app'

urlpatterns = [
    path('all-employees/', views.ListAllEmployee.as_view(), name = 'all_employees'),
    path('SuccessView/', views.SuccessView.as_view(), name = 'correct'),
    # path('ListByDepartmentFinances/', views.ListByDepartment.as_view()),
    path('two-employees/', views.ListAllEmployeeByFour.as_view()),
    path('ListByDepartment/<short_name>', views.ListByDepartment.as_view(), name = 'listByDepartment'),
    path('ListByWord/', views.ListByDepartmentByWord.as_view()),
    path('ListEmployeeAbility/', views.ListAbilityEmployeeWithIdOne.as_view()),
    path('EmployeeDetailView/<pk>', views.EmployeeDetailView.as_view()),
    path('EmployeeDetailViewKwargs/<pk>', views.EmployeeDetailViewKwargs.as_view(), name='empleado_detail'),
    path('addEmployee/', views.EmployeeCreateView.as_view(), name='add_employee'),
    path('EditEmployee/<pk>/', views.EmployeeUpdateView.as_view(), name='modify_employee'),
    path('DeleteEmployee/<pk>/', views.DeleteEmployeeView.as_view(), name='delete_employee'),
    path('', views.InicioView.as_view(), name='Inicio'),
    path('list-employees-admin/', views.ListEmployeeAdmin.as_view(), name='list-employees-admin')
]

test_project/urls.py
from django.contrib import admin #Trae las plantillas de admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applications.department.urls')),
    path('', include('applications.person.urls')),
    path('', include('applications.home.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_project/templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu>
            <li class="menu-text">Empleados</1i>
            <li><a href="{% url 'person_app:all_employees' %}">Listar</a></1i>
            <li><a href="{% url 'departament_app:list-deparment' %}">Departamentos</a></1i>
            <li><a href="{% url 'person_app:list-employees-admin' %}">Administrar</a></1i>
            <li><a href="{% url 'departament_app:new-deparment' %}">Nuevo Departamento</a></1i>
        </ul>
    </div>
    <div class="top-bar-right">
        <ul class="menu">
            <li><input type="search" placeholder="Buscar Empleado..."></1i>
            <li><a type="button" class="button success" href="{% url 'person_app:add_employee' %}">Registrar nuevo</a></l1i>
        </ul>
    </div>
</div>